services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    command: npm run start
    volumes:
      - ./backend/src/:/app/src/
    env_file: ./backend/.env

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3006:3000
  #   command: npm run dev
  #   volumes:
  #     - ./frontend/src/:/app/src/

  db:
    image: postgres
    #restart: always
    volumes:
      - postgres_volumes:/var/lib/postgresql/data
    ports:
      - 5433:5432
    env_file: .env

volumes:
  postgres_volumes:
