GET http://localhost:5000/ads

###

GET http://localhost:5000/ads/search?title=boa

###

GET http://localhost:5000/ads?categoryIn=1

###

GET http://localhost:5000/ads?loc

###

GET http://localhost:5000/ads/19

###

POST http://localhost:5000/ads
Content-Type: application/json

{

  "title": "plane to sell",
  "description": "YOLOlolo",
  "author": "rike.seller@gmail.com",
  "imgUrl" : "https://cdn.pixabay.com/photo/2017/09/28/13/38/double-decker-2795557_1280.jpg",
  "location": "Paris", 
  "price": 150,
  "category": { "id": 3 },
  "tags": [{ "id": 2 }, { "id": 3 }]
}

###

DELETE http://localhost:5000/ads/12

###

PATCH http://localhost:5000/ads/1
Content-Type: application/json

{
  
  "category": 3,
  "tags": [{ "id": 2 }]
}