GET http://localhost:5000/tags

###

POST http://localhost:5000/tags
Content-Type: application/json

{
  "name": "orange" 
}

###

DELETE http://localhost:5000/tags/4

###

PATCH http://localhost:5000/tags/2
Content-Type: application/json

{
 "name": "bleu"
}