GET http://localhost:3000/tags

###

POST http://localhost:3000/tags
Content-Type: application/json

{
  "name": "sweet" 
}

###

DELETE http://localhost:3000/tags/4

###

PATCH http://localhost:3000/tags/2
Content-Type: application/json

{
 "name": "maison"
}